#!perl
package OtpFaults;

use strict;
use warnings;

use base 'Exporter';

our @EXPORT = qw(get_otp_faults get_errors_from_fault_word);

my %otp_faults = 
(
#    // First word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_no_fault                       => { word => 0  , bit => 0x00000000 , msg => "OTP No Fault 0x%X"                                  , threshold => "FAULT_DISABLE" , maxrate => "ONEHOUR" }        , 
    otp_general_fault                  => { word => 0  , bit => 0x00000001 , msg => "OTP General Fault 0x%X"                             , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_wrong_sp_fpga_vers             => { word => 0  , bit => 0x00000002 , msg => "OTP Wrong SP FPGA 0x%X"                             , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_pci_error_detected             => { word => 0  , bit => 0x00000004 , msg => "OTP PCI Error Detected 0x%X"                        , threshold => "0U"            , maxrate => "TENSECONDS" }     , 
    otp_pcie_error_detected            => { word => 0  , bit => 0x00000008 , msg => "OTP PCIe Error Detected 0x%X"                       , threshold => "0U"            , maxrate => "TENSECONDS" }     , 
    otp_vp_card_outputs_error          => { word => 0  , bit => 0x00000010 , msg => "OTP VP Card Outputs Error 0x%X"                     , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_io_control_register_error      => { word => 0  , bit => 0x00000020 , msg => "OTP IO Control Register Error 0x%X"                 , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_fc_signals_register_error      => { word => 0  , bit => 0x00000040 , msg => "OTP Fibre Channel Signals Error 0x%X"               , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_power_supply_register_error    => { word => 0  , bit => 0x00000080 , msg => "OTP Power Supply Register Error 0x%X"               , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_sdma_initialization_error      => { word => 0  , bit => 0x00000100 , msg => "OTP SDMA Initialization Error 0x%X"                 , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_bsp_initialization_error       => { word => 0  , bit => 0x00000200 , msg => "OTP bspPCInit() Error 0x%X"                         , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_process_dp_maint_server_error  => { word => 0  , bit => 0x00000400 , msg => "OTP Process DP Maint Server Error 0x%X"             , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_video_comp_memory_error        => { word => 0  , bit => 0x00000800 , msg => "OTP Video Compression Memory Error 0x%X"            , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_video_input_memory_error       => { word => 0  , bit => 0x00001000 , msg => "OTP Video Input Memory Error 0x%X"                  , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_default_isr_error              => { word => 0  , bit => 0x00002000 , msg => "OTP Default ISR Error 0x%X"                         , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_get_physical_address_error     => { word => 0  , bit => 0x00004000 , msg => "OTP GetPhysicalAddress() Error 0x%X"                , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_init_video_input_error         => { word => 0  , bit => 0x00008000 , msg => "OTP initialize_video_input() Error 0x%X"            , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_enable_input_source_error      => { word => 0  , bit => 0x00010000 , msg => "OTP enable_input_source() Error 0x%X"               , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_get_clock_time_error           => { word => 0  , bit => 0x00020000 , msg => "OTP GetClockTime() Error 0x%X"                      , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_gt_dma_init_error              => { word => 0  , bit => 0x00040000 , msg => "OTP gtDMAInit() Error 0x%X"                         , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_gt_dma_control_error           => { word => 0  , bit => 0x00080000 , msg => "OTP gtDMAControl() Error 0x%X"                      , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_gt_dma_start_error             => { word => 0  , bit => 0x00100000 , msg => "OTP gtDMAStart() Error 0x%X"                        , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_set_bright_level_error         => { word => 0  , bit => 0x00200000 , msg => "OTP set_brightness_level() Error 0x%X"              , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_get_bright_level_error         => { word => 0  , bit => 0x00400000 , msg => "OTP get_brightness_level() Error 0x%X"              , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_set_gamma_table_error          => { word => 0  , bit => 0x00800000 , msg => "OTP set_gamma_tbl_from_number Error 0x%X"           , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_pci_performance_error          => { word => 0  , bit => 0x01000000 , msg => "OTP PCI Performance Fell Under Threshold 0x%X"      , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_stof_pulses_threshold_error    => { word => 0  , bit => 0x02000000 , msg => "OTP STOF Pulse Rate fell below 70Hz 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_main_loop_threshold_error      => { word => 0  , bit => 0x04000000 , msg => "OTP OTP_Main() loop fell below 50Hz 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_seal_1_ogl_threshold_error     => { word => 0  , bit => 0x08000000 , msg => "OTP SEAL 1 OGL FPS fell below 50Hz 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_seal_3_ogl_threshold_error     => { word => 0  , bit => 0x10000000 , msg => "OTP SEAL 3 OGL FPS fell below 12Hz 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vid_record_threshold_error     => { word => 0  , bit => 0x20000000 , msg => "OTP Video Rec Stopped for more than 20 frames 0x%X" , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_vid_input_register_error       => { word => 0  , bit => 0x40000000 , msg => "OTP Video Input Register Read Error 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vid_rec_register_error         => { word => 0  , bit => 0x80000000 , msg => "OTP Video Recording Register Read Error 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Second word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_fc_under_threshold_error       => { word => 1  , bit => 0x00000001 , msg => "OTP Fibre Channel Rate Under Threshold 0x%X"        , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_under_threshold_error       => { word => 1  , bit => 0x00000002 , msg => "OTP Firewire Rate Under Threshold 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_periodic_overrun_error         => { word => 1  , bit => 0x00000004 , msg => "OTP pcd_perform_periodic() ran over 800uS 0x%X"     , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_du_serial_timeout_error        => { word => 1  , bit => 0x00000008 , msg => "OTP DU Returns a DU Serial Timeout Error 0x%X"      , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_fcav_1_timeout_error           => { word => 1  , bit => 0x00000010 , msg => "OTP FC/AV Video Input 1 Timeout 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_fcav_2_timeout_error           => { word => 1  , bit => 0x00000020 , msg => "OTP FC/AV Video Input 2 Timeout 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_draw_under_threshold_error     => { word => 1  , bit => 0x00000040 , msg => "OTP Drawing Time Under Threshold 0x%X"              , threshold => "0U"            , maxrate => "0LL" }            , 
    otp_fibre_chan_sync_error          => { word => 1  , bit => 0x00000080 , msg => "OTP FC Sync Rate Under Threshold 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_crc_threshold_error         => { word => 1  , bit => 0x00000100 , msg => "OTP FC CRC Error Rate Threshold 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_frame_discard_thresh_error  => { word => 1  , bit => 0x00000200 , msg => "OTP FC Frame Discard Threshold 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_transmit_msg_error          => { word => 1  , bit => 0x00000400 , msg => "OTP FC Transmit Message Error 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_receive_msg_error           => { word => 1  , bit => 0x00000800 , msg => "OTP FC Receive Message Error 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_firewire_sync_error            => { word => 1  , bit => 0x00001000 , msg => "OTP FW Sync Rate Threshold 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_bus_reset_threshold         => { word => 1  , bit => 0x00002000 , msg => "OTP FW Bus Resets Threshold 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port0_inactive_interrupt    => { word => 1  , bit => 0x00004000 , msg => "OTP FC Inactive Port 0 Interrupt 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port1_inactive_interrupt    => { word => 1  , bit => 0x00008000 , msg => "OTP FC Inactive Port 1 Interrupt 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port2_inactive_interrupt    => { word => 1  , bit => 0x00010000 , msg => "OTP FC Inactive Port 2 Interrupt 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port3_inactive_interrupt    => { word => 1  , bit => 0x00020000 , msg => "OTP FC Inactive Port 3 Interrupt 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port0_loss_of_sync          => { word => 1  , bit => 0x00040000 , msg => "OTP FC Loss Of Sync Port 0 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port1_loss_of_sync          => { word => 1  , bit => 0x00080000 , msg => "OTP FC Loss Of Sync Port 1 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port2_loss_of_sync          => { word => 1  , bit => 0x00100000 , msg => "OTP FC Loss Of Sync Port 2 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_port3_loss_of_sync          => { word => 1  , bit => 0x00200000 , msg => "OTP FC Loss Of Sync Port 3 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp1_over_temperature           => { word => 1  , bit => 0x00400000 , msg => "OTP SP Module Over Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_vp_over_temperature            => { word => 1  , bit => 0x00800000 , msg => "OTP VP Module Over Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_io_over_temperature            => { word => 1  , bit => 0x01000000 , msg => "OTP IO Module Over Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_fc_over_temperature            => { word => 1  , bit => 0x02000000 , msg => "OTP FC Module Over Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_lvps_over_temperature          => { word => 1  , bit => 0x04000000 , msg => "OTP LVPS Module Over Temperature 0x%X"              , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_internal_fence_post_error      => { word => 1  , bit => 0x08000000 , msg => "OTP Internal Overwrite Error 0x%X"                  , threshold => "0U"            , maxrate => "TWOSECONDS" }     , 
    otp_no_dp_main_ready_error         => { word => 1  , bit => 0x10000000 , msg => "OTP DP Maint Ready Flag Never Occurred 0x%X"        , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_mpeg_engine_error              => { word => 1  , bit => 0x20000000 , msg => "OTP MPEG Engine Error 0x%X"                         , threshold => "0U"            , maxrate => "TWOSECONDS" }     , 
    otp_mpeg_engine_unknown_error      => { word => 1  , bit => 0x40000000 , msg => "OTP MPEG Engine Unknown State Error 0x%X"           , threshold => "0U"            , maxrate => "TWOSECONDS" }     , 
    otp_du_bad_dc_software_part_num    => { word => 1  , bit => 0x80000000 , msg => "OTP DU Bad DC Software Part Number 0x%X"            , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
#    // Third word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_bad_eu_part_num                => { word => 2  , bit => 0x00000001 , msg => "OTP Bad EU Part Number Error 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_bad_eu_serial_num              => { word => 2  , bit => 0x00000002 , msg => "OTP Bad EU Serial Number Error 0x%X"                , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_bad_du_part_num                => { word => 2  , bit => 0x00000004 , msg => "OTP Bad DU Part Number Error 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_bad_du_serial_num              => { word => 2  , bit => 0x00000008 , msg => "OTP Bad DU Serial Number Error 0x%X"                , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_communication_failed        => { word => 2  , bit => 0x00000010 , msg => "OTP DU Communication Failed 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_both_dp_cst_logs_in_progress   => { word => 2  , bit => 0x00000020 , msg => "OTP Both DP Fault Logs in Progress 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_too_long_wait_for_dp_log       => { word => 2  , bit => 0x00000040 , msg => "OTP Too Long Waiting for DP Fault Log 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ogl1_not_drawing_error         => { word => 2  , bit => 0x00000080 , msg => "OTP OGL 1 has not drawn in 1/4 second 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ogl2_not_drawing_error         => { word => 2  , bit => 0x00000100 , msg => "OTP OGL 2 has not drawn in 1/4 second 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sbl_not_valid_for_config       => { word => 2  , bit => 0x00000200 , msg => "OTP SBL is not valid for this config 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_ebl_not_valid_for_config       => { word => 2  , bit => 0x00000400 , msg => "OTP EBL is not valid for this config 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_sp_fpga_not_valid_for_config   => { word => 2  , bit => 0x00000800 , msg => "OTP SP FPGA is not valid for this config 0x%X"      , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_sp_cpu_not_valid_for_config    => { word => 2  , bit => 0x00001000 , msg => "OTP SP CPU is not valid for this config 0x%X"       , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_dp_cpu_not_valid_for_config    => { word => 2  , bit => 0x00002000 , msg => "OTP DP CPU is not valid for this config 0x%X"       , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_niu_not_valid_for_config    => { word => 2  , bit => 0x00004000 , msg => "OTP IO NIU is not valid for this config 0x%X"       , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_fc_niu_not_valid_for_config    => { word => 2  , bit => 0x00008000 , msg => "OTP FC NIU is not valid for this config 0x%X"       , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_ll_not_valid_for_config     => { word => 2  , bit => 0x00010000 , msg => "OTP IO LL is not valid for this config 0x%X"        , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_vpp_fpga_not_valid_for_config  => { word => 2  , bit => 0x00020000 , msg => "OTP VPP FPGA is not valid for this config 0x%X"     , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_vr_fpga_not_valid_for_config   => { word => 2  , bit => 0x00040000 , msg => "OTP VR FPGA is not valid for this config 0x%X"      , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_duma_not_valid_for_config      => { word => 2  , bit => 0x00080000 , msg => "OTP DUMA Core is not valid for this config 0x%X"    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_dp_boot_not_valid_for_config   => { word => 2  , bit => 0x00100000 , msg => "OTP DP Boot is not valid for this config 0x%X"      , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_kdi_not_valid_for_config       => { word => 2  , bit => 0x00200000 , msg => "OTP KDI is not valid for this config 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_usr_fs_not_valid_for_config    => { word => 2  , bit => 0x00400000 , msg => "OTP User FS is not valid for this config 0x%X"      , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_local_fs_not_valid_for_config  => { word => 2  , bit => 0x00800000 , msg => "OTP Local FS is not valid for this config 0x%X"     , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_sbl_unrecog_for_config         => { word => 2  , bit => 0x01000000 , msg => "OTP SBL is unrecognized 0x%X"                       , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_ebl_unrecog_for_config         => { word => 2  , bit => 0x02000000 , msg => "OTP EBL is unrecognized 0x%X"                       , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_sp_fpga_unrecog_for_config     => { word => 2  , bit => 0x04000000 , msg => "OTP SP FPGA is unrecognized 0x%X"                   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_sp_cpu_unrecog_for_config      => { word => 2  , bit => 0x08000000 , msg => "OTP SP CPU is unrecognized 0x%X"                    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_dp_cpu_unrecog_for_config      => { word => 2  , bit => 0x10000000 , msg => "OTP DP CPU is unrecognized 0x%X"                    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_niu_unrecog_for_config      => { word => 2  , bit => 0x20000000 , msg => "OTP IO NIU is unrecognized 0x%X"                    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_fc_niu_unrecog_for_config      => { word => 2  , bit => 0x40000000 , msg => "OTP FC NIU is unrecognized 0x%X"                    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_ll_unrecog_for_config       => { word => 2  , bit => 0x80000000 , msg => "OTP IO LL is unrecognized 0x%X"                     , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
#    // Fourth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_vpp_fpga_unrecog_for_config    => { word => 3  , bit => 0x00000001 , msg => "OTP VPP FPGA is unrecognized 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_vr_fpga_unrecog_for_config     => { word => 3  , bit => 0x00000002 , msg => "OTP VR FPGA is unrecognized 0x%X"                   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_duma_unrecog_for_config        => { word => 3  , bit => 0x00000004 , msg => "OTP DUMA Core is unrecognized 0x%X"                 , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_dp_boot_unrecog_for_config     => { word => 3  , bit => 0x00000008 , msg => "OTP DP Boot is unrecognized 0x%X"                   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_kdi_unrecog_for_config         => { word => 3  , bit => 0x00000010 , msg => "OTP KDI is unrecognized  0x%X"                      , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_usr_fs_unrecog_for_config      => { word => 3  , bit => 0x00000020 , msg => "OTP User FS is unrecognized 0x%X"                   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_local_fs_unrecog_for_config    => { word => 3  , bit => 0x00000040 , msg => "OTP Local FS is unrecognized 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_detect_dp_fault_log_corruption => { word => 3  , bit => 0x00000080 , msg => "OTP Detects DP Fault Log Corruption 0x%X"           , threshold => "0U"            , maxrate => "FIVEMINUTES" }    , 
    otp_dp_1p5_volt_failure            => { word => 3  , bit => 0x00000100 , msg => "DP 1p5 Volt Power Supply FAILURE! 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_3p0_volt_failure            => { word => 3  , bit => 0x00000200 , msg => "DP 3p0 Volt Power Supply FAILURE! 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_1p0_volt_failure            => { word => 3  , bit => 0x00000400 , msg => "DP 1p0 Volt Power Supply FAILURE! 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_2p0_volt_failure            => { word => 3  , bit => 0x00000800 , msg => "DP 2p0 Volt Power Supply FAILURE! 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_ram_term_volt_failure       => { word => 3  , bit => 0x00001000 , msg => "DP RAM Term Volt Power Supply FAILURE! 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_io_link_needs_recovery         => { word => 3  , bit => 0x00002000 , msg => "PCI IO Link Needs Recovery 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_link_needs_recovery         => { word => 3  , bit => 0x00004000 , msg => "PCI FC Link Needs Recovery 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_nt_link_needs_recovery         => { word => 3  , bit => 0x00008000 , msg => "PCI NT Link Needs Recovery 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_driver_recovery_needed         => { word => 3  , bit => 0x00010000 , msg => "OTP Periodic Driver Recovery Needed 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_driver_recovery_in_progress    => { word => 3  , bit => 0x00020000 , msg => "OTP Driver Recovery In Progress 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_maint_server_dp_not_ready      => { word => 3  , bit => 0x00040000 , msg => "OTP DP Maint Server thinks DP Not Ready 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_maint_server_invalid_buf       => { word => 3  , bit => 0x00080000 , msg => "OTP DP Maint Server Invalid Buffer 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_maint_server_unrecog_msg       => { word => 3  , bit => 0x00100000 , msg => "OTP DP Maint Server Unrecoginzied Msg 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_bad_serial_packet              => { word => 3  , bit => 0x00200000 , msg => "OTP Bad Communication Packet from MTE 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiChannelFailure           => { word => 3  , bit => 0x00400000 , msg => "OTP ATI Channel Failure 0x%X"                       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiProcessorFailure         => { word => 3  , bit => 0x00800000 , msg => "OTP ATI Processing Failure 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiInterfaceFailure         => { word => 3  , bit => 0x01000000 , msg => "OTP ATI Interface Failure 0x%X"                     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrGLInvalidEnum         => { word => 3  , bit => 0x02000000 , msg => "OTP ATI OpenGL Invalid Enum 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrGLInvalidValue        => { word => 3  , bit => 0x04000000 , msg => "OTP ATI OpenGL Invalid Value 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrGLInvalidOperation    => { word => 3  , bit => 0x08000000 , msg => "OTP ATI OpenGL Invalid Operation 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrGLStackOverflow       => { word => 3  , bit => 0x10000000 , msg => "OTP ATI OpenGL Stack Overflow 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrGLOutOfMemory         => { word => 3  , bit => 0x20000000 , msg => "OTP ATI OpenGL Out Of Memory 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiFrameWriteFailure        => { word => 3  , bit => 0x40000000 , msg => "OTP ATI Frame Write Failure 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglInvalidMessageID         => { word => 3  , bit => 0x80000000 , msg => "OTP ATI Invalid Message ID 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Fifth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_mt_oglInvalidOpcode            => { word => 4  , bit => 0x00000001 , msg => "OTP ATI Invalid Opcode 0x%X"                        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglMessageIncomplete        => { word => 4  , bit => 0x00000002 , msg => "OTP ATI Message Incomplete 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglBeginEndMismatch         => { word => 4  , bit => 0x00000004 , msg => "OTP ATI OpenGL Begin End Mismatch 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglChannelRxBufferFull      => { word => 4  , bit => 0x00000008 , msg => "OTP ATI Channel Rx Buffer Full 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglInWorkQueueError         => { word => 4  , bit => 0x00000010 , msg => "OTP ATI In Work Queue Error 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglBufferTableError         => { word => 4  , bit => 0x00000020 , msg => "OTP ATI Buffer Table Full 0x%X"                     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglWindowTableError         => { word => 4  , bit => 0x00000040 , msg => "OTP ATI Window Table Error 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglContextTableError        => { word => 4  , bit => 0x00000080 , msg => "OTP ATI Context Table Error 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglTextureTableError        => { word => 4  , bit => 0x00000100 , msg => "OTP ATI Texture Table Error 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_oglDisplayListTableError    => { word => 4  , bit => 0x00000200 , msg => "OTP ATI OpenGL Display List Error 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrL3ShaderUnavailable   => { word => 4  , bit => 0x00000400 , msg => "OTP ATI L3 Shader Unavailable 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrL3VideoDiscrepancy    => { word => 4  , bit => 0x00000800 , msg => "OTP ATI L3 Video Discrepency 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mt_atiErrL3InvalidOperation    => { word => 4  , bit => 0x00001000 , msg => "OTP ATI L3 Invalid Operation 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ogl_begin_block_error          => { word => 4  , bit => 0x00002000 , msg => "OTP Bad Return from OGL Begin BLock 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ogl_end_block_error            => { word => 4  , bit => 0x00004000 , msg => "OTP Bad Return from OGL End BLock 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_initial_cst_failed             => { word => 4  , bit => 0x00008000 , msg => "OTP Initial CST tests failed in Kernel Main 0x%X"   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_initial_niu_dma_test_failed    => { word => 4  , bit => 0x00010000 , msg => "OTP Initial NIU DMA Tests Failed 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_load_corrupt          => { word => 4  , bit => 0x00020000 , msg => "OTP DP Flags Load Corrupt 0x%X"                     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_waiting_to_load       => { word => 4  , bit => 0x00040000 , msg => "OTP DP Flags Waiting to Load 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_loading_in_progress         => { word => 4  , bit => 0x00080000 , msg => "OTP DP Flags Loading In Progress 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flash_write_protected       => { word => 4  , bit => 0x00100000 , msg => "OTP DP Flags Flash is Write Protected 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_post_fail             => { word => 4  , bit => 0x00200000 , msg => "OTP DP Flags POST Fail 0x%X"                        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_hw_exception          => { word => 4  , bit => 0x00400000 , msg => "OTP DP Flags Hardware Exception 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_rs232_fail            => { word => 4  , bit => 0x00800000 , msg => "OTP DP Flags RS-232 Failure 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_sdram_fail            => { word => 4  , bit => 0x01000000 , msg => "OTP DP Flags SDRAM Failure 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_ecc1_fail             => { word => 4  , bit => 0x02000000 , msg => "OTP DP Flags ECC 1 Bit Failure 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_ecc2_fail             => { word => 4  , bit => 0x04000000 , msg => "OTP DP Flags ECC 2 Bit Failure 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_data_cache_fail       => { word => 4  , bit => 0x08000000 , msg => "OTP DP Flags Data Cache Failure 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_instruct_cache_fail   => { word => 4  , bit => 0x10000000 , msg => "OTP DP Flags Instruction Cache Failure 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_boot_crc_fail         => { word => 4  , bit => 0x20000000 , msg => "OTP DP Flags Boot CRC Failure 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_boot_copy_fail        => { word => 4  , bit => 0x40000000 , msg => "OTP DP Flags Boot Copy Failure 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_kdi_crc_fail          => { word => 4  , bit => 0x80000000 , msg => "OTP DP Flags KDI CRC Failure 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Sixth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_dp_flags_usrfs_crc_fail        => { word => 5  , bit => 0x00000001 , msg => "OTP DP Flags User FS CRC Failure 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_localfs_crc_fail      => { word => 5  , bit => 0x00000002 , msg => "OTP DP Flags Local FS CRC Failure 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_flags_kdi_copy_fail         => { word => 5  , bit => 0x00000004 , msg => "OTP DP Flags KDI Copy Failure 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_bad_right_guess             => { word => 5  , bit => 0x00000008 , msg => "OTP DP Incorrect Right Side 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_bad_left_guess              => { word => 5  , bit => 0x00000010 , msg => "OTP DP Incorrect Left Side 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mpeg_init_failed               => { word => 5  , bit => 0x00000020 , msg => "OTP mpeg_init() call Failed 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mpeg_config_buffers_failed     => { word => 5  , bit => 0x00000040 , msg => "OTP config_mpeg_buffers() Failed 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mpeg_enable_failed             => { word => 5  , bit => 0x00000080 , msg => "OTP enable_mpeg() call Failed 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mpeg_disable_failed            => { word => 5  , bit => 0x00000100 , msg => "OTP disable_mpeg() call Failed 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_lm_part_num_cross_check_fail   => { word => 5  , bit => 0x00000200 , msg => "OTP LM Part Number Cross Check Failed 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_initial_pci_early_test_failed  => { word => 5  , bit => 0x00000400 , msg => "OTP Early Kernel Main PCI Tests Failed 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_register_read_test_fail        => { word => 5  , bit => 0x00000800 , msg => "OTP Repative Register Read Test Failed 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_register_dma_test_fail         => { word => 5  , bit => 0x00001000 , msg => "OTP DMA Register Read Test Failed 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_eu_pn_mismatch_flash_nvram     => { word => 5  , bit => 0x00002000 , msg => "OTP EU PN Mismatch Flash vs NVRAM 0x%X"             , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_eu_sn_mismatch_flash_nvram     => { word => 5  , bit => 0x00004000 , msg => "OTP EU SN Mismatch Flash vs NVRAM 0x%X"             , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_no_dp_ready_flag_error         => { word => 5  , bit => 0x00008000 , msg => "OTP DP Ready Flag Never Occurred 0x%X"              , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_fw_link_layer_receive_overrun  => { word => 5  , bit => 0x00010000 , msg => "OTP FW Link Layer Receiver Was Overrun 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_8532_to_io_8114_lanes       => { word => 5  , bit => 0x00020000 , msg => "OTP SP 8532 to IO 8114 Lane Width Error 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_8532_to_marvell_8114_lanes  => { word => 5  , bit => 0x00040000 , msg => "OTP SP 8532 to Marvell 8114 Lane Width Error 0x%X"  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_8532_to_fc_8114_lanes       => { word => 5  , bit => 0x00080000 , msg => "OTP SP 8532 to FC 8114 Lane Width Error 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_8532_to_vp_8532_lanes       => { word => 5  , bit => 0x00100000 , msg => "OTP SP 8532 to VP 8532 Lane Width Error 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_8532_to_sp_8532_lanes       => { word => 5  , bit => 0x00200000 , msg => "OTP VP 8532 to SP 8532 Lane Width Error 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_8532_to_marvell_8114_lanes  => { word => 5  , bit => 0x00400000 , msg => "OTP VP 8532 to Marvell 8114 Lane Width Error 0x%X"  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_8532_to_ati_asic_lanes      => { word => 5  , bit => 0x00800000 , msg => "OTP VP 8532 to ATI ASIC Lane Width Error 0x%X"      , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_8532_to_vr_fpga_lanes       => { word => 5  , bit => 0x01000000 , msg => "OTP VP 8532 to Vid Rec Lane Width Error 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_8532_to_vi_fpga_lanes       => { word => 5  , bit => 0x02000000 , msg => "OTP VP 8532 to Vid In Lane Width Error 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_no_dp_opengl_ready_error       => { word => 5  , bit => 0x04000000 , msg => "OTP DP OpenGL Ready Flag not set Error 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_periodic_returned_fail         => { word => 5  , bit => 0x08000000 , msg => "OTP Periodic returned FAIL 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_single_bit_err_CS0         => { word => 5  , bit => 0x10000000 , msg => "OTP DDR Single Bit Error CS0 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_double_bit_err_CS0         => { word => 5  , bit => 0x20000000 , msg => "OTP DDR Double Bit Error CS0 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_single_bit_err_CS1         => { word => 5  , bit => 0x40000000 , msg => "OTP DDR Single Bit Error CS1 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_double_bit_err_CS1         => { word => 5  , bit => 0x80000000 , msg => "OTP DDR Double Bit Error CS1 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // The Seventh and Eighth word are handled in a different way. They contain the DU Extended Fault information.
#    // Nineth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_ddr_single_bit_err_CS2         => { word => 8  , bit => 0x00000001 , msg => "OTP DDR Single Bit Error CS2 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_double_bit_err_CS2         => { word => 8  , bit => 0x00000002 , msg => "OTP DDR Double Bit Error CS2 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_single_bit_err_CS3         => { word => 8  , bit => 0x00000004 , msg => "OTP DDR Single Bit Error CS3 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_double_bit_err_CS3         => { word => 8  , bit => 0x00000008 , msg => "OTP DDR Double Bit Error CS3 Register 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sram_single_bit_err            => { word => 8  , bit => 0x00000010 , msg => "OTP DDR Single Bit SRAM Register 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sram_double_bit_err            => { word => 8  , bit => 0x00000020 , msg => "OTP DDR Double Bit SRAM Register 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_power_management_failure       => { word => 8  , bit => 0x00000040 , msg => "OTP Power Management Failure 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_bl_over_temperature            => { word => 8  , bit => 0x00000080 , msg => "OTP DU Backlight Over Temperature 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_amlcd_over_temperature         => { word => 8  , bit => 0x00000100 , msg => "OTP DU AMLCD Over Temperature 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_hps_over_temperature           => { word => 8  , bit => 0x00000200 , msg => "OTP DU HPS Micro Over Temperature 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_emi_over_temperature           => { word => 8  , bit => 0x00000400 , msg => "OTP DU EMI Over Temperature 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dicca_over_temperature         => { word => 8  , bit => 0x00000800 , msg => "OTP DU DI CCA Over Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_eti_too_large               => { word => 8  , bit => 0x00001000 , msg => "OTP SP ETI Meter Value Too Large 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_vp_eti_too_large               => { word => 8  , bit => 0x00002000 , msg => "OTP VP ETI Meter Value Too Large 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_eti_too_large               => { word => 8  , bit => 0x00004000 , msg => "OTP IO ETI Meter Value Too Large 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_fc_eti_too_large               => { word => 8  , bit => 0x00008000 , msg => "OTP FC ETI Meter Value Too Large 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_lvps_eti_too_large             => { word => 8  , bit => 0x00010000 , msg => "OTP LVPS ETI Meter Value Too Large 0x%X"            , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_dp_heartbeat_failed            => { word => 8  , bit => 0x00020000 , msg => "OTP DP Heartbeat has Failed 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_cpu_error_cause_nonzero     => { word => 8  , bit => 0x00040000 , msg => "OTP SP CPU Error Cause is NonZero 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_pci0_error_cause_nonzero    => { word => 8  , bit => 0x00080000 , msg => "OTP SP PCI0 Error Cause is NonZero 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_pci1_error_cause_nonzero    => { word => 8  , bit => 0x00100000 , msg => "OTP SP PCI1 Error Cause is NonZero 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_cpu_error_cause_nonzero     => { word => 8  , bit => 0x00200000 , msg => "OTP DP CPU Error Cause is NonZero 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_pci0_error_cause_nonzero    => { word => 8  , bit => 0x00400000 , msg => "OTP DP PCI0 Error Cause is NonZero 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_pci1_error_cause_nonzero    => { word => 8  , bit => 0x00800000 , msg => "OTP DP PCI1 Error Cause is NonZero 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_bus_reset_init_threshold    => { word => 8  , bit => 0x01000000 , msg => "OTP FW Bus Resets Init Threshold 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_bus_reset_change_threshold  => { word => 8  , bit => 0x02000000 , msg => "OTP FW Bus Resets Change Threshold 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_eti_not_sequential          => { word => 8  , bit => 0x04000000 , msg => "OTP SP ETI is Not Sequential 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_vp_eti_not_sequential          => { word => 8  , bit => 0x08000000 , msg => "OTP VP ETI is Not Sequential 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_eti_not_sequential          => { word => 8  , bit => 0x10000000 , msg => "OTP IO ETI is Not Sequential 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_fc_eti_not_sequential          => { word => 8  , bit => 0x20000000 , msg => "OTP FC ETI is Not Sequential 0x%X"                  , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_lvps_eti_not_sequential        => { word => 8  , bit => 0x40000000 , msg => "OTP LVPS ETI is Not Sequential 0x%X"                , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_no_ipc_vp_config_done_flag     => { word => 8  , bit => 0x80000000 , msg => "OTP VP Config Done not set in IPC Flags 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Tenth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_no_ipc_right_side_flag         => { word => 9  , bit => 0x00000001 , msg => "OTP Node Right Side not set in IPC Flags 0x%X"      , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_bad_ipc_right_side_flag        => { word => 9  , bit => 0x00000002 , msg => "OTP Node Right Side set in IPC Flags 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_in_err_exceeds_50ms       => { word => 9  , bit => 0x00000004 , msg => "OTP Discrete In Mismatch Exceeds 50ms 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_in_err_exceeds_1s         => { word => 9  , bit => 0x00000008 , msg => "OTP Discrete In Mismatch Exceeds 1s 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_in_err_exceeds_3s         => { word => 9  , bit => 0x00000010 , msg => "OTP Discrete In Mismatch Exceeds 3s 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_out_err_exceeds_100ms     => { word => 9  , bit => 0x00000020 , msg => "OTP Discrete Out Mismatch Exceeds 50ms 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_out_err_exceeds_1s        => { word => 9  , bit => 0x00000040 , msg => "OTP Discrete Out Mismatch Exceeds 1s 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_out_err_exceeds_3s        => { word => 9  , bit => 0x00000080 , msg => "OTP Discrete Out Mismatch Exceeds 3s 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_initialize_maint_buf_fail      => { word => 9  , bit => 0x00000100 , msg => "OTP InitializeMaintenanceBuffers() failed 0x%X"     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_init_dp_fault_maint_fail       => { word => 9  , bit => 0x00000200 , msg => "OTP InitializeDPFaultMaintStruct() failed 0x%X"     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_bl_eti_too_large               => { word => 9  , bit => 0x00000400 , msg => "OTP DU BL ETI Meter Value Too Large 0x%X"           , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_lcd_eti_too_large              => { word => 9  , bit => 0x00000800 , msg => "OTP DU LCD ETI Meter Value Too Large 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_di_eti_too_large               => { word => 9  , bit => 0x00001000 , msg => "OTP DU DI ETI Meter Value Too Large 0x%X"           , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_ts_eti_too_large               => { word => 9  , bit => 0x00002000 , msg => "OTP DU TS ETI Meter Value Too Large 0x%X"           , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_emi_eti_too_large              => { word => 9  , bit => 0x00004000 , msg => "OTP DU EMI ETI Meter Value Too Large 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_sp_eti_too_small               => { word => 9  , bit => 0x00008000 , msg => "OTP SP ETI Meter Value Too Small 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_vp_eti_too_small               => { word => 9  , bit => 0x00010000 , msg => "OTP VP ETI Meter Value Too Small 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_io_eti_too_small               => { word => 9  , bit => 0x00020000 , msg => "OTP IO ETI Meter Value Too Small 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_fc_eti_too_small               => { word => 9  , bit => 0x00040000 , msg => "OTP FC ETI Meter Value Too Small 0x%X"              , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_lvps_eti_too_small             => { word => 9  , bit => 0x00080000 , msg => "OTP LVPS ETI Meter Value Too Small 0x%X"            , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_bl_eti_too_small               => { word => 9  , bit => 0x00100000 , msg => "OTP DU BL ETI Meter Value Too Small 0x%X"           , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_lcd_eti_too_small              => { word => 9  , bit => 0x00200000 , msg => "OTP DU LCD ETI Meter Value Too Small 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_di_eti_too_small               => { word => 9  , bit => 0x00400000 , msg => "OTP DU DI ETI Meter Value Too Small 0x%X"           , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_ts_eti_too_small               => { word => 9  , bit => 0x00800000 , msg => "OTP DU TS ETI Meter Value Too Small 0x%X"           , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_emi_eti_too_small              => { word => 9  , bit => 0x01000000 , msg => "OTP DU EMI ETI Meter Value Too Small 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_loss_of_du_communications      => { word => 9  , bit => 0x02000000 , msg => "OTP DU Loss of DU Communications 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp1_under_temperature          => { word => 9  , bit => 0x04000000 , msg => "OTP SP Module Under Temperature 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_vp_under_temperature           => { word => 9  , bit => 0x08000000 , msg => "OTP VP Module Under Temperature 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_io_under_temperature           => { word => 9  , bit => 0x10000000 , msg => "OTP IO Module Under Temperature 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_fc_under_temperature           => { word => 9  , bit => 0x20000000 , msg => "OTP FC Module Under Temperature 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_lvps_under_temperature         => { word => 9  , bit => 0x40000000 , msg => "OTP LVPS Module Under Temperature 0x%X"             , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_bl_under_temperature           => { word => 9  , bit => 0x80000000 , msg => "OTP DU Backlight Under Temperature 0x%X"            , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
#    // Eleventh word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_amlcd_under_temperature        => { word => 10 , bit => 0x00000001 , msg => "OTP DU AMLCD Under Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_hps_under_temperature          => { word => 10 , bit => 0x00000002 , msg => "OTP DU HPS Micro Under Temperature 0x%X"            , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_emi_under_temperature          => { word => 10 , bit => 0x00000004 , msg => "OTP DU EMI Under Temperature 0x%X"                  , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_dicca_under_temperature        => { word => 10 , bit => 0x00000008 , msg => "OTP DU DI CCA Under Temperature 0x%X"               , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } , 
    otp_lm_nvram_mem_test_failure      => { word => 10 , bit => 0x00000010 , msg => "OTP Mem Test Failure of LM portion of NVRAM 0x%X"   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_du_fan_on_thresh_out_of_bound  => { word => 10 , bit => 0x00000020 , msg => "OTP DU PHM Fan On Threshold Out of Bounds 0x%X"     , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_fan_off_thresh_out_of_bound => { word => 10 , bit => 0x00000040 , msg => "OTP DU PHM Fan Off Threshold Out of Bounds 0x%X"    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_unexpected_reset            => { word => 10 , bit => 0x00000080 , msg => "OTP DU Unexpected Reset 0x%X"                       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp_frame_diff_too_large        => { word => 10 , bit => 0x00000100 , msg => "OTP DP Frame Diff Too Large 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_unexpected_mt_fault            => { word => 10 , bit => 0x00000200 , msg => "OTP ATI MT Unexpected Fault 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_du_touch_x_diff_too_large      => { word => 10 , bit => 0x00000400 , msg => "OTP DU Touch X Diff Too Large 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_du_touch_y_diff_too_large      => { word => 10 , bit => 0x00000800 , msg => "OTP DU Touch Y Diff Too Large 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vid_rec_did_not_halt           => { word => 10 , bit => 0x00001000 , msg => "OTP Video Recording Did Not Halt 0x%X"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_internal_pointer_error         => { word => 10 , bit => 0x00002000 , msg => "OTP Internal Pointer Error 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vid_rec_on_off_failed          => { word => 10 , bit => 0x00004000 , msg => "OTP Video Recording On/Off Failed 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_du_dicca_sw_ver_wrong          => { word => 10 , bit => 0x00008000 , msg => "OTP DU DICCA SW Version Wrong 0x%X"                 , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_dicca_boot_sw_ver_wrong     => { word => 10 , bit => 0x00010000 , msg => "OTP DU DICCA Boot SW Version Wrong 0x%X"            , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_dicca_dwl_sw_ver_wrong      => { word => 10 , bit => 0x00020000 , msg => "OTP DU DICCA Download SW Version Wrong 0x%X"        , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_dicca_config_sw_ver_wrong   => { word => 10 , bit => 0x00040000 , msg => "OTP DU DICCA Config SW Version Wrong 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_dicca_lut_sw_ver_wrong      => { word => 10 , bit => 0x00080000 , msg => "OTP DU DICCA Look Up Table SW Version Wrong 0x%X"   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_ts_sw_ver_wrong             => { word => 10 , bit => 0x00100000 , msg => "OTP DU Touch Screen SW Version Wrong 0x%X"          , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_ts_boot_sw_ver_wrong        => { word => 10 , bit => 0x00200000 , msg => "OTP DU Touch Screen Boot SW Version Wrong 0x%X"     , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_ts_dwl_sw_ver_wrong         => { word => 10 , bit => 0x00400000 , msg => "OTP DU Touch Screen Download SW Version Wrong 0x%X" , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_ts_config_sw_ver_wrong      => { word => 10 , bit => 0x00800000 , msg => "OTP DU Touch Screen Config SW Version Wrong 0x%X"   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_ts_lut_sw_ver_wrong         => { word => 10 , bit => 0x01000000 , msg => "OTP DU Touch Screen LUT SW Version Wrong 0x%X"      , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_du_amlcd_ver_wrong             => { word => 10 , bit => 0x02000000 , msg => "OTP DU AMLCD Version Wrong 0x%X"                    , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_struct_size_mismatch           => { word => 10 , bit => 0x04000000 , msg => "OTP Structure Size Mismatch 0x%X"                   , threshold => "0U"            , maxrate => "ONEHOUR" }        , 
    otp_flash_sector_erase_too_long    => { word => 10 , bit => 0x08000000 , msg => "OTP Flash Sector Erase Took Too Long 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_flash_sector_erase_fail        => { word => 10 , bit => 0x10000000 , msg => "OTP Flash Sector Erase Failed 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_flash_erase_fail               => { word => 10 , bit => 0x20000000 , msg => "OTP Flash Erase Failed 0x%X"                        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_flash_data_write_too_long      => { word => 10 , bit => 0x40000000 , msg => "OTP Flash Data Write Took Too Long 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_flash_data_write_fail          => { word => 10 , bit => 0x80000000 , msg => "OTP Flash Data Write Failed 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Twelveth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_flash_data_verify_fail         => { word => 11 , bit => 0x00000001 , msg => "OTP Flash Data Verify Failed 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_marvell_sram_memory_error      => { word => 11 , bit => 0x00000002 , msg => "OTP Marvell SRAM Memory Test Failed 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_background_memory_error        => { word => 11 , bit => 0x00000004 , msg => "OTP Background Task Memory Test Failed 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_background_flash_error         => { word => 11 , bit => 0x00000008 , msg => "OTP Background Task Flash Test Failed 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_input_discretes_not_valid      => { word => 11 , bit => 0x00000010 , msg => "OTP Input Discretes are not valid 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_link_layerb_interrupt       => { word => 11 , bit => 0x00000020 , msg => "OTP FW Link LayerB Interrupt 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_b_micro_timing_error        => { word => 11 , bit => 0x00000040 , msg => "OTP FW B Micro Timing Error 0x%X"                   , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_vs_busb_mode_change         => { word => 11 , bit => 0x00000080 , msg => "OTP FW VS Bus B Mode Change 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_chipb_error                 => { word => 11 , bit => 0x00000100 , msg => "OTP FW CHIP B Error 0x%X"                           , threshold => "10U"           , maxrate => "FIVESECONDS" }    , 
    otp_fw_stofb_vertical_parity_err   => { word => 11 , bit => 0x00000200 , msg => "OTP FW STOFB Vertical Parity Err 0x%X"              , threshold => "1U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_link_layera_interrupt       => { word => 11 , bit => 0x00000400 , msg => "OTP FW Link Layer A Interrupt 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_a_micro_timing_error        => { word => 11 , bit => 0x00000800 , msg => "OTP FW A Micro Timing Error 0x%X"                   , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_vs_busa_mode_change         => { word => 11 , bit => 0x00001000 , msg => "OTP FW VS Bus A Mode Change 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_chipa_error                 => { word => 11 , bit => 0x00002000 , msg => "OTP FW CHIP A Error 0x%X"                           , threshold => "10U"           , maxrate => "FIVESECONDS" }    , 
    otp_fw_stofa_vertical_parity_err   => { word => 11 , bit => 0x00004000 , msg => "OTP FW STOFA Vertical Parity Err 0x%X"              , threshold => "1U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_extended_interrupt_err      => { word => 11 , bit => 0x00008000 , msg => "OTP FW Unexpected Extended Interrupt 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_dma_abort                   => { word => 11 , bit => 0x00010000 , msg => "OTP FW DMA Abort 0x%X"                              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_interrupt_fifo_full         => { word => 11 , bit => 0x00020000 , msg => "OTP FW Interrupt FIFO Full 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_transmit_message_error      => { word => 11 , bit => 0x00040000 , msg => "OTP FW Transmit Message Error 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_asm_memory_parity_error     => { word => 11 , bit => 0x00080000 , msg => "OTP FW ASM Memory Parity Error 0x%X"                , threshold => "1U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_trc_parity_error            => { word => 11 , bit => 0x00100000 , msg => "OTP FW TRC Parity Error 0x%X"                       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_nrs_parity_error            => { word => 11 , bit => 0x00200000 , msg => "OTP FW NRS Parity Error 0x%X"                       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_rrc_parity_error            => { word => 11 , bit => 0x00400000 , msg => "OTP FW RRC Parity Error 0x%X"                       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_tcb_rcb_parity_error        => { word => 11 , bit => 0x00800000 , msg => "OTP FW TCB RCB Parity Error 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_host_read_parity_error      => { word => 11 , bit => 0x01000000 , msg => "OTP FW Host Read Parity Error 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_dma_abort_detected          => { word => 11 , bit => 0x02000000 , msg => "OTP FW DMA Abort Detected 0x%X"                     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_discrete_out_sense_not_valid   => { word => 11 , bit => 0x04000000 , msg => "OTP Discrete Output Sense Invalid 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_bar_timeout                 => { word => 11 , bit => 0x08000000 , msg => "OTP FW BAR Timeout 0x%X"                            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_background_link_layer_ver_err  => { word => 11 , bit => 0x10000000 , msg => "OTP FW Link Layer Bkgnd Ver 0x%X"                   , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_background_link_layer_dm_err   => { word => 11 , bit => 0x20000000 , msg => "OTP FW Link Layer Bkgnd DM Err 0x%X"                , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_reg_set_error    => { word => 11 , bit => 0x40000000 , msg => "OTP FW Link Layer Register Set Error 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_link_layer_a_vers_error     => { word => 11 , bit => 0x80000000 , msg => "OTP FW Link Layer A Version Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
#    // Thirteenth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_fw_link_layer_b_vers_error     => { word => 12 , bit => 0x00000001 , msg => "OTP FW Link Layer B Version Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_atf_not_clear  => { word => 12 , bit => 0x00000002 , msg => "OTP FW Link Layer A ATF Not Clear 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_atf_not_clear  => { word => 12 , bit => 0x00000004 , msg => "OTP FW Link Layer B ATF Not Clear 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_atf_full       => { word => 12 , bit => 0x00000008 , msg => "OTP FW Link Layer A ATF Full 0x%X"                  , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_atf_full       => { word => 12 , bit => 0x00000010 , msg => "OTP FW Link Layer B ATF Full 0x%X"                  , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_dm_error       => { word => 12 , bit => 0x00000020 , msg => "OTP FW Link Layer A Data Mover Error 0x%X"          , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_dm_error       => { word => 12 , bit => 0x00000040 , msg => "OTP FW Link Layer B Data Mover Error 0x%X"          , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_selfid_error   => { word => 12 , bit => 0x00000080 , msg => "OTP FW Link Layer A Self ID Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_selfid_error   => { word => 12 , bit => 0x00000100 , msg => "OTP FW Link Layer B Self ID Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_trans_stuck    => { word => 12 , bit => 0x00000200 , msg => "OTP FW Link Layer A Transmitter Stuck 0x%X"         , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_trans_stuck    => { word => 12 , bit => 0x00000400 , msg => "OTP FW Link Layer B Transmitter Stuck 0x%X"         , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_grf_overflow   => { word => 12 , bit => 0x00000800 , msg => "OTP FW Link Layer A Busy Ack GRF Ovflw 0x%X"        , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_grf_overflow   => { word => 12 , bit => 0x00001000 , msg => "OTP FW Link Layer B Busy Ack GRF Ovflw 0x%X"        , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_tc_error       => { word => 12 , bit => 0x00002000 , msg => "OTP FW Link Layer A Transaction Code Err 0x%X"      , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_tc_error       => { word => 12 , bit => 0x00004000 , msg => "OTP FW Link Layer B Transaction Code Err 0x%X"      , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_dm_ack_err     => { word => 12 , bit => 0x00008000 , msg => "OTP FW Link Layer A Data Mover Ack Err 0x%X"        , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_dm_ack_err     => { word => 12 , bit => 0x00010000 , msg => "OTP FW Link Layer B Data Mover Ack Err 0x%X"        , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_mc_error       => { word => 12 , bit => 0x00020000 , msg => "OTP FW Link Layer A Micro-Interface Err 0x%X"       , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_mc_error       => { word => 12 , bit => 0x00040000 , msg => "OTP FW Link Layer B Micro-Interface Err 0x%X"       , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_cycle_lost     => { word => 12 , bit => 0x00080000 , msg => "OTP FW Link Layer A Cycle Lost 0x%X"                , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_cycle_lost     => { word => 12 , bit => 0x00100000 , msg => "OTP FW Link Layer B Cycle Lost 0x%X"                , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_cycle_arb_fail => { word => 12 , bit => 0x00200000 , msg => "OTP FW Link Layer A Cycle Arb Failed 0x%X"          , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_cycle_arb_fail => { word => 12 , bit => 0x00400000 , msg => "OTP FW Link Layer B Cycle Arb Failed 0x%X"          , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_a_iso_arb_fail   => { word => 12 , bit => 0x00800000 , msg => "OTP FW Link Layer A Isoch Arb Failed 0x%X"          , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_link_layer_b_iso_arb_fail   => { word => 12 , bit => 0x01000000 , msg => "OTP FW Link Layer B Isoch Arb Failed 0x%X"          , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_chip_a_access_timeout       => { word => 12 , bit => 0x02000000 , msg => "OTP FW Chip A Access Timeout 0x%X"                  , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_chip_b_access_timeout       => { word => 12 , bit => 0x04000000 , msg => "OTP FW Chip B Access Timeout 0x%X"                  , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_security_kernel_lock_error  => { word => 12 , bit => 0x08000000 , msg => "OTP FW Security Kernel Lock Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_sec_kernel_invalid_access   => { word => 12 , bit => 0x10000000 , msg => "OTP FW Sec Kernel Invalid Access 0x%X"              , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_lpa_command_fifo_full       => { word => 12 , bit => 0x20000000 , msg => "OTP FW Low Pri A Command FIFO Full 0x%X"            , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_hpa_command_fifo_full       => { word => 12 , bit => 0x40000000 , msg => "OTP FW High Pri A Command FIFO Full 0x%X"           , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_lpb_command_fifo_full       => { word => 12 , bit => 0x80000000 , msg => "OTP FW Low Pri B Command FIFO Full 0x%X"            , threshold => "0U"            , maxrate => "ONESECOND" }      , 
#    // Fourteenth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_fw_hpb_command_fifo_full       => { word => 13 , bit => 0x00000001 , msg => "OTP FW High Pri B Command FIFO Full 0x%X"           , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_a_busy                 => { word => 13 , bit => 0x00000002 , msg => "OTP FW Port A Busy 0x%X"                            , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_b_busy                 => { word => 13 , bit => 0x00000004 , msg => "OTP FW Port B Busy 0x%X"                            , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_0_stalled              => { word => 13 , bit => 0x00000008 , msg => "OTP FW Port 0 Stalled 0x%X"                         , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_1_stalled              => { word => 13 , bit => 0x00000010 , msg => "OTP FW Port 1 Stalled 0x%X"                         , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_0_lp_fifo_write_error  => { word => 13 , bit => 0x00000020 , msg => "OTP FW Port 0 LP FIFO Write Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_1_lp_fifo_write_error  => { word => 13 , bit => 0x00000040 , msg => "OTP FW Port 1 LP FIFO Write Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_0_hp_fifo_write_error  => { word => 13 , bit => 0x00000080 , msg => "OTP FW Port 0 HP FIFO Write Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_port_1_hp_fifo_write_error  => { word => 13 , bit => 0x00000100 , msg => "OTP FW Port 1 HP FIFO Write Error 0x%X"             , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_transmit_msg_err_threshold  => { word => 13 , bit => 0x00000200 , msg => "OTP FW Transmit Message Error Threshold 0x%X"       , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_receive_msg_err_threshold   => { word => 13 , bit => 0x00000400 , msg => "OTP FW Receive Message Error Threshold 0x%X"        , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_invalid_mode_change         => { word => 13 , bit => 0x00000800 , msg => "OTP FW Invalid Mode Change Request 0x%X"            , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_pcd_perform_periodic_rate      => { word => 13 , bit => 0x00001000 , msg => "OTP pcd_perform_periodic() Call Rate Low 0x%X"      , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_isai_error                  => { word => 13 , bit => 0x00002000 , msg => "OTP FW Internal STOF A Interrupt 0x%X"              , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_isbi_error                  => { word => 13 , bit => 0x00004000 , msg => "OTP FW Internal STOF B Interrupt 0x%X"              , threshold => "0U"            , maxrate => "ONESECOND" }      , 
    otp_fw_tx_under_threshold_error    => { word => 13 , bit => 0x00008000 , msg => "OTP FW TX Rate Under Threshold 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_rx_under_threshold_error    => { word => 13 , bit => 0x00010000 , msg => "OTP FW RX Rate Under Threshold 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_opengl_egl_bad_return          => { word => 13 , bit => 0x00020000 , msg => "OTP OpenGL EGL Bad Return Value 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_above_bit_error_rate_limit  => { word => 13 , bit => 0x00040000 , msg => "OTP FW Above Bit Error Rate Limit 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_phy_connect_error           => { word => 13 , bit => 0x00080000 , msg => "OTP FW Phy Connect Error 0x%X"                      , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_phy_rxok_error              => { word => 13 , bit => 0x00100000 , msg => "OTP FW Phy RxOK Error 0x%X"                         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_left_node_a_phy_port_0_err  => { word => 13 , bit => 0x00200000 , msg => "OTP FW Left Node A Phy P0 Err VS1 U6 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_left_node_a_phy_port_1_err  => { word => 13 , bit => 0x00400000 , msg => "OTP FW Left Node A Phy P1 Err VS2 U10 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_left_node_a_phy_port_2_err  => { word => 13 , bit => 0x00800000 , msg => "OTP FW Left Node A Phy P2 Err VSS U12 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_left_node_b_phy_port_0_err  => { word => 13 , bit => 0x01000000 , msg => "OTP FW Left Node B Phy P0 Err MSS U9 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_left_node_b_phy_port_1_err  => { word => 13 , bit => 0x02000000 , msg => "OTP FW Left Node B Phy P1 Err MS U8 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_left_node_b_phy_port_2_err  => { word => 13 , bit => 0x04000000 , msg => "OTP FW Left Node B Phy P2 Err MSI U7 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_right_node_a_phy_port_0_err => { word => 13 , bit => 0x08000000 , msg => "OTP FW Right Node A Phy P0 Err VS1 U3 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_right_node_a_phy_port_1_err => { word => 13 , bit => 0x10000000 , msg => "OTP FW Right Node A Phy P1 Err VS2 U2 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_right_node_a_phy_port_2_err => { word => 13 , bit => 0x20000000 , msg => "OTP FW Right Node A Phy P2 Err VSS U1 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_right_node_b_phy_port_0_err => { word => 13 , bit => 0x40000000 , msg => "OTP FW Right Node B Phy P0 Err MSS U11 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fw_right_node_b_phy_port_1_err => { word => 13 , bit => 0x80000000 , msg => "OTP FW Right Node B Phy P1 Err MS U5 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Fifteenth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_fw_right_node_b_phy_port_2_err => { word => 14 , bit => 0x00000001 , msg => "OTP FW Right Node B Phy P2 Err MSI U4 0x%X"         , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_startup_adc_register_error     => { word => 14 , bit => 0x00000002 , msg => "OTP Cold/Warm Start ADC Reg Err 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dimming_adc_register_error     => { word => 14 , bit => 0x00000004 , msg => "OTP Dimming Bus ADC Reg Err 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_plx_8114_id_register_error  => { word => 14 , bit => 0x00000008 , msg => "OTP SP PLX 8114 ID Reg Err 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_plx_8532_id_register_error  => { word => 14 , bit => 0x00000010 , msg => "OTP SP PLX 8532 ID Reg Err 0x%X"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_niu5_plx_8114_id_register_err  => { word => 14 , bit => 0x00000020 , msg => "OTP NIU 5 PLX 8114 ID Reg Err 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_niu4_plx_8114_id_register_err  => { word => 14 , bit => 0x00000040 , msg => "OTP NIU 4 PLX 8114 ID Reg Err 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_marvel_pci_host_0_config_err   => { word => 14 , bit => 0x00000080 , msg => "OTP Marvel PCI Host 0 Config 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_marvel_pci_host_1_config_err   => { word => 14 , bit => 0x00000100 , msg => "OTP Marvel PCI Host 1 Config 0x%X"                  , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vr_has_frozen                  => { word => 14 , bit => 0x00000200 , msg => "OTP Video Recording Has Frozen 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ati_device_vendor_id_err       => { word => 14 , bit => 0x00000400 , msg => "OTP ATI Device/Vendor ID Error 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_pex_eeprom_wait_timeout        => { word => 14 , bit => 0x00000800 , msg => "OTP PEX EEPROM Wait Timeout Err 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_in_flagged_invalid        => { word => 14 , bit => 0x00001000 , msg => "OTP Discrete Inputs Flagged Invalid 0x%X"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_out_flagged_invalid       => { word => 14 , bit => 0x00002000 , msg => "OTP Discrete Outputs Flagged Invalid 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_disc_sense_flagged_invalid     => { word => 14 , bit => 0x00004000 , msg => "OTP Disc Out Sense Flagged Invalid 0x%X"            , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_background_dp_memory_err       => { word => 14 , bit => 0x00008000 , msg => "OTP Background SP to DP Memory Error 0x%X"          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp2_over_temperature           => { word => 14 , bit => 0x00010000 , msg => "OTP SP CPU Over Temperature 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp1_over_temperature           => { word => 14 , bit => 0x00020000 , msg => "OTP DP Module Over Temperature 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_dp2_over_temperature           => { word => 14 , bit => 0x00040000 , msg => "OTP DP CPU Over Temperature 0x%X"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_pscr_access_not_valid          => { word => 14 , bit => 0x00080000 , msg => "OTP PS Control Register Access Invalid 0x%X"        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_pscr_access_not_done           => { word => 14 , bit => 0x00100000 , msg => "OTP PS Control Register Access Not Done 0x%X"       , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_mpeg_is_corrupted              => { word => 14 , bit => 0x00200000 , msg => "OTP MPEG buffers are Corrupted 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_sp_eti_not_incrementing        => { word => 14 , bit => 0x00400000 , msg => "OTP SP ETI Not Incrementing 0x%x"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_eti_not_incrementing        => { word => 14 , bit => 0x00800000 , msg => "OTP VP ETI Not Incrementing 0x%x"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_io_eti_not_incrementing        => { word => 14 , bit => 0x01000000 , msg => "OTP IO ETI Not Incrementing 0x%x"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_eti_not_incrementing        => { word => 14 , bit => 0x02000000 , msg => "OTP FC ETI Not Incrementing 0x%x"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_lvps_eti_not_incrementing      => { word => 14 , bit => 0x04000000 , msg => "OTP LVPS ETI Not Incrementing 0x%x"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_sp_eti_not_valid               => { word => 14 , bit => 0x08000000 , msg => "OTP SP ETI Not Valid 0x%x"                          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_vp_eti_not_valid               => { word => 14 , bit => 0x10000000 , msg => "OTP VP ETI Not Valid 0x%x"                          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_io_eti_not_valid               => { word => 14 , bit => 0x20000000 , msg => "OTP IO ETI Not Valid 0x%x"                          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_fc_eti_not_valid               => { word => 14 , bit => 0x40000000 , msg => "OTP FC ETI Not Valid 0x%x"                          , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_lvps_eti_not_valid             => { word => 14 , bit => 0x80000000 , msg => "OTP LVPS ETI Not Valid 0x%x"                        , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
#    // Sixteenth word of the GP BIT faults on the OTP GUI and the ESS GUI log report
    otp_1_volt_fail                    => { word => 15 , bit => 0x00000001 , msg => "OTP 1 volt MPP Input Fail 0x%x"                     , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_1_pnt_5_volt_fail              => { word => 15 , bit => 0x00000002 , msg => "OTP 1.5 volt MPP Input Fail 0x%x"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_2_pnt_5_volt_fail              => { word => 15 , bit => 0x00000004 , msg => "OTP 2.5 volt MPP Input Fail 0x%x"                   , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_ddr_trm_volt_fail              => { word => 15 , bit => 0x00000008 , msg => "OTP DDR Termination Voltage Fail 0x%x"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    , 
    otp_critical_error_reset           => { word => 15 , bit => 0x00000010 , msg => "OTP Critical Error Reset 0x%X"                      , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_dma_engine_2_min_timeout       => { word => 15 , bit => 0x00000020 , msg => "OTP DMA Engine Timeout, Over 2 Mins 0x%x"           , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_sample_at_reset_fault          => { word => 15 , bit => 0x00000040 , msg => "OTP Sample at Reset Fault 0x%x"                     , threshold => "0U"            , maxrate => "FIVEMINUTES" }    ,
    otp_detect_sp_fault_log_corruption => { word => 15 , bit => 0x00000080 , msg => "OTP Detects SP Fault Log Corruption 0x%X"           , threshold => "0U"            , maxrate => "FIVEMINUTES" }    , 
    otp_stop_on_temperature            => { word => 15 , bit => 0x00000100 , msg => "OTP Declares Stop On Temperature 0x%X"              , threshold => "0U"            , maxrate => "FIVEMINUTES" }    , 
    otp_vp1_over_temperature           => { word => 15 , bit => 0x00000200 , msg => "OTP VP ADT 7461 Over Temperature 0x%X"              , threshold => "0U"            , maxrate => "FIVEMINUTES" }    ,
    otp_vp2_over_temperature           => { word => 15 , bit => 0x00000400 , msg => "OTP VP ATI ASIC Over Temperature 0x%X"              , threshold => "0U"            , maxrate => "FIVEMINUTES" }    ,
    otp_mpeg_buf_release_error         => { word => 15 , bit => 0x00000800 , msg => "OTP MPEG Buffer Release Error 0x%X"                 , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_pci_invalid_data_error         => { word => 15 , bit => 0x00001000 , msg => "OTP PCI Invalid Data Error 0x%x"                    , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_invalid_pointer                => { word => 15 , bit => 0x00002000 , msg => "OTP Invalid Pointer Value 0x%x"                     , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_sp_fpga_stalled_error          => { word => 15 , bit => 0x00004000 , msg => "OTP SP FPGA Updates Have Stalled 0x%x"              , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_uncommanded_watchdog_reset     => { word => 15 , bit => 0x00008000 , msg => "OTP Uncommanded Watchdog Reset Detected 0x%x"       , threshold => "0U"            , maxrate => "FOURHOURS"   }    ,
    otp_uncommanded_system_reset       => { word => 15 , bit => 0x00010000 , msg => "OTP Uncommanded System Reset Detected 0x%x"         , threshold => "0U"            , maxrate => "FOURHOURS"   }    ,
    otp_pci_6540_nt_bridge_error       => { word => 15 , bit => 0x00020000 , msg => "OTP PCI-X 6540 Bridge Error 0x%x"                   , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } ,
    otp_sp_test_dp_memory_error        => { word => 15 , bit => 0x00040000 , msg => "OTP SP Test of DP Memory Error 0x%x"                , threshold => "0U"            , maxrate => "FIFTEENSECONDS" } ,
    otp_duplicate_mac_error            => { word => 15 , bit => 0x00080000 , msg => "OTP Duplicate MAC Address Error 0x%X"               , threshold => "0U"            , maxrate => "FOURHOURS"   }    ,
    otp_bad_mac_address_error          => { word => 15 , bit => 0x00100000 , msg => "OTP Bad MAC Address Error 0x%X"                     , threshold => "0U"            , maxrate => "FOURHOURS"   }    ,
    otp_internal_case_error            => { word => 15 , bit => 0x00200000 , msg => "OTP Internal Case Statement Error 0x%X"             , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_fc_niu_insane                  => { word => 15 , bit => 0x00400000 , msg => "OTP FC NIU Insane 0x%X"                             , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_main_loop_stalled_error        => { word => 15 , bit => 0x00800000 , msg => "OTP Main Loop is Stalled Error 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_fc_extended_interrupt_error    => { word => 15 , bit => 0x01000000 , msg => "OTP FC Extended Interrupt Error 0x%X"               , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_fc_dma_abort_error             => { word => 15 , bit => 0x02000000 , msg => "OTP FC DMA Abort Error 0x%X"                        , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_fc_asm_memory_parity_error     => { word => 15 , bit => 0x04000000 , msg => "OTP FC ASM Memory Parity Error 0x%X"                , threshold => "0U"            , maxrate => "FIVESECONDS" }    ,
    otp_fault_table_terminator         => { word => 16 , bit => 0x00000000 , msg => "OTP Fault Table Terminator 0x%X"                    , threshold => "0U"            , maxrate => "0LL" }            , 
);

sub get_otp_faults 
{
    return %otp_faults;
}

sub get_errors_from_fault_word
{
    my $searchWord = $_[0];
    my $searchBits = $_[1];
    my @results = ();

    for (my $i = 0; $i < 32; $i++)
    {
        my $bit = 2 ** $i;
        if (($bit & $searchBits) != 0)
        {
            while (my ($key, $value) = each(%otp_faults))
            {
                if (($value->{word} == $searchWord) && ($value->{bit} == $bit))
                {
                    push(@results, $value->{msg});
                }
            }
        }
    }
    return @results;
}

1;
